kind: Project
apiVersion: project.openshift.io/v1
metadata:
  name: choco67-dev
  uid: 1009cf04-d615-4c4d-87cd-f6e61c924de5
  resourceVersion: '6650788094'
  creationTimestamp: '2026-07-25T07:57:29Z'
  labels:
    toolchain.dev.openshift.com/tier: base1ns
    toolchain.dev.openshift.com/space: choco67
    openshift-pipelines.tekton.dev/namespace-trusted-configmaps-version: 1.23.0
    kubernetes.io/metadata.name: choco67-dev
    modelmesh-enabled: 'true'
    openshift-pipelines.tekton.dev/namespace-reconcile-version: 1.23.0
    name: choco67-dev
    pod-security.kubernetes.io/warn: baseline
    toolchain.dev.openshift.com/provider: codeready-toolchain
    pod-security.kubernetes.io/audit: baseline
    toolchain.dev.openshift.com/templateref: base1ns-dev-d757b66-d757b66
    pod-security.kubernetes.io/warn-version: latest
    opendatahub.io/dashboard: 'true'
    toolchain.dev.openshift.com/type: dev
    pod-security.kubernetes.io/audit-version: latest
  annotations:
    openshift.io/description: choco67-dev
    openshift.io/display-name: choco67-dev
    openshift.io/requester: choco67
    toolchain.dev.openshift.com/last-applied-configuration: '{"apiVersion":"v1","kind":"Namespace","metadata":{"annotations":{"openshift.io/description":"choco67-dev","openshift.io/display-name":"choco67-dev","openshift.io/requester":"choco67"},"labels":{"modelmesh-enabled":"true","name":"choco67-dev","opendatahub.io/dashboard":"true","toolchain.dev.openshift.com/provider":"codeready-toolchain","toolchain.dev.openshift.com/space":"choco67","toolchain.dev.openshift.com/type":"dev"},"name":"choco67-dev"}}'
    toolchain.dev.openshift.com/last-applied-space-roles: '[{"templateRef":"base1ns-admin-88b275d-88b275d","usernames":["choco67"]}]'
    openshift.io/sa.scc.supplemental-groups: 1005180000/10000
    openshift.io/sa.scc.mcs: 's0:c72,c34'
    openshift.io/sa.scc.uid-range: 1005180000/10000
    security.openshift.io/MinimallySufficientPodSecurityStandard: baseline
  managedFields:
    - manager: cluster-policy-controller
      operation: Apply
      apiVersion: v1
      time: '2026-07-25T07:57:29Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            'f:openshift.io/sa.scc.mcs': {}
            'f:openshift.io/sa.scc.supplemental-groups': {}
            'f:openshift.io/sa.scc.uid-range': {}
    - manager: pod-security-admission-label-synchronization-controller
      operation: Apply
      apiVersion: v1
      time: '2026-07-25T07:59:16Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            'f:security.openshift.io/MinimallySufficientPodSecurityStandard': {}
          'f:labels':
            'f:pod-security.kubernetes.io/audit': {}
            'f:pod-security.kubernetes.io/audit-version': {}
            'f:pod-security.kubernetes.io/warn': {}
            'f:pod-security.kubernetes.io/warn-version': {}
    - manager: member-operator
      operation: Update
      apiVersion: v1
      time: '2026-07-25T07:57:30Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:openshift.io/description': {}
            'f:openshift.io/display-name': {}
            'f:openshift.io/requester': {}
            'f:toolchain.dev.openshift.com/last-applied-configuration': {}
            'f:toolchain.dev.openshift.com/last-applied-space-roles': {}
          'f:labels':
            'f:toolchain.dev.openshift.com/templateref': {}
            'f:toolchain.dev.openshift.com/provider': {}
            'f:opendatahub.io/dashboard': {}
            .: {}
            'f:toolchain.dev.openshift.com/space': {}
            'f:toolchain.dev.openshift.com/type': {}
            'f:kubernetes.io/metadata.name': {}
            'f:modelmesh-enabled': {}
            'f:toolchain.dev.openshift.com/tier': {}
            'f:name': {}
    - manager: openshift-pipelines-operator
      operation: Update
      apiVersion: v1
      time: '2026-07-25T07:59:17Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:labels':
            'f:openshift-pipelines.tekton.dev/namespace-reconcile-version': {}
            'f:openshift-pipelines.tekton.dev/namespace-trusted-configmaps-version': {}
spec:
  finalizers:
    - kubernetes
status:
  phase: Active
